[package]
name = "cj-sema"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Cangjie semantic analysis: symbol tables, name resolution, type checking"

[dependencies]
cj-ast = { path = "../cj-ast" }
cj-diag = { path = "../cj-diag" }
cj-lexer = { path = "../cj-lexer" }
cj-parser = { path = "../cj-parser" }
libc = "0.2"
libloading = "0.8"
rayon = "1"