#!/usr/bin/env python3
"""Generate the std-type member tables for completion.rs from official cjlsp
expected items (cases 090=Array, 087=String, 127/161=Option).

Emits a Rust snippet defining ARRAY_MEMBERS / STRING_MEMBERS / OPTION_MEMBERS
as `&[(&str, u32, &str, &str, u32, &str)]` rows:
  (label, kind, detail, insertText, insertTextFormat, filterText)
"""
import json, re, os, sys

BASE = "/root/Code/cangjie/cangjie_test/testsuites/HLT/Tools/cjlsp"

def expected_items(case):
    name = f"textDocument_completion_{case:03d}.info"
    txt = open(f"{BASE}/testcases/autotestcase/completion/{name}", encoding='utf-8').read()
    exp = txt.split("Rev#")[1]
    for l in exp.splitlines():
        l = l.strip()
        if l.startswith("{"):
            j = json.loads(l)
            res = j.get("result")
            if isinstance(res, list):
                return res
    return []

def rust_str(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')

def emit(name, items):
    out = [f"const {name}: &[(&str, u32, &str, &str, u32, &str)] = &["]
    for it in items:
        label = it.get("label", "")
        kind = it.get("kind", 0)
        detail = it.get("detail", "")
        ins = it.get("insertText", "")
        fmt = it.get("insertTextFormat", 1)
        filt = it.get("filterText", "")
        out.append(
            f'    ("{rust_str(label)}", {kind}, "{rust_str(detail)}", '
            f'"{rust_str(ins)}", {fmt}, "{rust_str(filt)}"),'
        )
    out.append("];")
    return "\n".join(out)

def main():
    array = expected_items(90)
    string = expected_items(87)
    option = expected_items(127)  # Option<T>.None / Some items
    print("// Auto-generated by tools/gen_std_tables.py — do not hand-edit.")
    print(f"// Array items: {len(array)}  String: {len(string)}  Option: {len(option)}")
    print()
    print(emit("ARRAY_MEMBERS", array))
    print()
    print(emit("STRING_MEMBERS", string))
    print()
    print(emit("OPTION_MEMBERS", option))
    print()

if __name__ == "__main__":
    main()
