#!/usr/bin/env python3
"""Generate cj-diag message templates from the official diagnostic .def files.

Sources:
  - cangjie_compiler/include/cangjie/Basic/DiagRefactor/DiagnosticParser.def (381)
  - DiagnosticLexer.def (111)
  - DiagnosticSema.def (414)
  - DiagnosticChir.def (50)

Each macro line has one of three shapes:
  ERROR(id, "msg")
  ERROR(id, "msg", "here")
  ERROR(id, "msg", "here", {"note", "note2"})
  WARNING(id, GROUP, "msg", "here", {notes...})

The generator emits:
  - a `DiagId` enum (stable ids, one variant per macro)
  - a lookup fn `fn template(id: DiagId) -> &'static DiagTemplate` with
    {message, here, notes} so formatters can render with
    `format!(template.message, args...)`.

Usage: python3 tools/gen_diags.py > crates/cj-diag/src/templates.rs
"""
from __future__ import annotations
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
# tools/ is inside cj-lang/, official sources are one level up under /root/Code/cangjie/
CANGJIE_DIR = os.path.dirname(HERE)
REPO = os.path.dirname(CANGJIE_DIR)
DIAG_DIR = os.path.join(REPO, "cangjie_compiler", "include", "cangjie", "Basic", "DiagRefactor")

FILES = [
    "DiagnosticParser.def",
    "DiagnosticLexer.def",
    "DiagnosticSema.def",
    "DiagnosticChir.def",
]

# ERROR(id, "msg", "here", {"note"})
RE_ERROR = re.compile(
    r'^(ERROR|WARNING)\(\s*([a-zA-Z0-9_]+)\s*,\s*'
    r'(?:[A-Z_]+\s*,\s*)?'  # optional group (WARNING)
    r'"((?:[^"\\]|\\.)*)"\s*(?:,\s*"((?:[^"\\]|\\.)*)")?\s*'
    r'(?:,\s*\{(.*?)\}\s*)?\)',
    re.S | re.M,
)

def parse_def(path: str) -> list[dict]:
    out = []
    with open(path, encoding="utf-8") as f:
        content = f.read()
    # strip comments
    content = re.sub(r'//.*', '', content)
    content = re.sub(r'/\*.*?\*/', '', content, flags=re.S)
    for m in RE_ERROR.finditer(content):
        kind, ident, msg, here, notes = m.group(1), m.group(2), m.group(3), m.group(4), m.group(5)
        # "here" may be empty string `""` (meaning no caret suffix)
        note_list = []
        if notes:
            for n in re.findall(r'"((?:[^"\\]|\\.)*)"', notes):
                note_list.append(n)
        out.append({
            "kind": kind,
            "ident": ident,
            "msg": msg,
            "here": here or "",
            "notes": note_list,
        })
    return out

def rust_str(s: str) -> str:
    """Render a rust string literal with proper escaping."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

def build() -> str:
    all_diags = []
    for fn in FILES:
        path = os.path.join(DIAG_DIR, fn)
        diags = parse_def(path)
        all_diags.extend(diags)
        print(f"// {fn}: {len(diags)} diags", file=sys.stderr)

    # dedupe by ident
    seen = {}
    for d in all_diags:
        seen.setdefault(d["ident"], d)
    all_diags = list(seen.values())

    lines = []
    w = lines.append
    w("// AUTO-GENERATED from official cangjie Diagnostic*.def — do not edit.")
    w("// Generated by tools/gen_diags.py. Category order: Parser, Lexer, Sema, Chir.")
    w("")
    w("#[allow(non_camel_case_types)]")
    w("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]")
    w("pub enum DiagId {")
    for d in all_diags:
        w(f"    /// {d['kind'].lower()} (from {d['ident']})")
        w(f"    {d['ident'].upper()},")
    w("}")
    w("")
    w("/// A diagnostic message template (official def entry).")
    w("#[derive(Debug, Clone, Copy)]")
    w("pub struct DiagTemplate {")
    w("    pub message: &'static str,")
    w("    /// Optional 'expected X here' caret suffix.")
    w("    pub here: Option<&'static str>,")
    w("    /// Optional 'note:' lines. Each may contain format placeholders.")
    w("    pub notes: &'static [&'static str],")
    w("}")
    w("")
    w("pub fn template(id: DiagId) -> DiagTemplate {")
    w("    match id {")
    for d in all_diags:
        notes_repr = "&[" + ", ".join(rust_str(n) for n in d["notes"]) + "]"
        here_repr = f'Some({rust_str(d["here"])})' if d["here"] else "None"
        w(f"        DiagId::{d['ident'].upper()} => DiagTemplate {{")
        w(f"            message: {rust_str(d['msg'])},")
        w(f"            here: {here_repr},")
        w(f"            notes: {notes_repr},")
        w(f"        }},")
    w("    }")
    w("}")
    w("")
    return "\n".join(lines)

if __name__ == "__main__":
    print(build())