// AUTO-GENERATED from official cangjie ASTKind.inc + Node.h — do not edit.
// Generated by tools/gen_ast.py. Node inventory mirrors the official
// compiler; compiler-internal fields are excluded (frontend/LSP only).

use crate::program::CodePos;

/// Primitive/builtin type kinds (official `BuiltInType`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PrimitiveKind {
    Int8,
    Int16,
    Int32,
    Int64,
    IntNative,
    UInt8,
    UInt16,
    UInt32,
    UInt64,
    UIntNative,
    Float16,
    Float32,
    Float64,
    Rune,
    Bool,
    Nothing,
    Unit,
    VArray,
    String,
}

/// Literal kind (official `LitConstKind`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LitKind {
    Integer,
    RuneByte,
    Float,
    Rune,
    String,
    JString,
    Bool,
    Unit,
    None,
}

/// Binary operator.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BinOp {
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    Exp,
    And,
    Or,
    BitAnd,
    BitOr,
    BitXor,
    LShift,
    RShift,
    Eq,
    Ne,
    Lt,
    Gt,
    Le,
    Ge,
    Coalesce,
    Pipe,
    Range,
    ClosedRange,
}

/// Unary operator.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnOp {
    Neg,
    Pos,
    Not,
    BitNot,
}

/// Assignment operator.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AssignOp {
    Assign,
    AddAssign,
    SubAssign,
    MulAssign,
    DivAssign,
    ModAssign,
    ExpAssign,
    AndAssign,
    OrAssign,
    BitAndAssign,
    BitOrAssign,
    BitXorAssign,
    LShiftAssign,
    RShiftAssign,
}

/// Generic type parameter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TypeParam {
    pub name: String,
    pub bounds: Vec<Type>,
    pub pos: CodePos,
}

/// Function/method parameter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Param {
    pub name: String,
    pub is_named: bool,
    pub ty: Type,
    pub default: Option<Expr>,
    pub pos: CodePos,
}

/// Function body.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Body {
    Block(Vec<Expr>),
    Empty,
}

/// Call argument.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FuncArg {
    pub name: Option<String>,
    pub value: Expr,
    pub pos: CodePos,
}

/// Interpolation part: literal text or embedded expression.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InterpPart {
    Text(String),
    Expr(Box<Expr>),
}

/// Catch clause.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CatchClause {
    pub name: Option<String>,
    pub ty: Option<Type>,
    pub body: Expr,
    pub pos: CodePos,
}

/// Match case.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MatchCase {
    pub pattern: Pattern,
    pub guard: Option<Expr>,
    pub body: Expr,
    pub pos: CodePos,
}

/// Enum case.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EnumCase {
    pub name: String,
    pub payloads: Vec<Type>,
    pub pos: CodePos,
}

/// Import spec.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ImportSpec {
    pub path: Vec<String>,
    pub glob: bool,
    pub selected: Vec<String>,
    pub pos: CodePos,
    /// Span of the imported package name (first..last path segment).
    pub name_pos: CodePos,
}

/// File (package + imports + decls).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct File {
    pub package: Option<String>,
    /// Position of the declared package name (start of first segment).
    pub package_pos: Option<CodePos>,
    pub imports: Vec<ImportSpec>,
    pub decls: Vec<Decl>,
    pub pos: CodePos,
}

/// Type node.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Type {
    /// REF_TYPE
    Ref {
        /// type name
        name: String,
        /// generic args
        args: Vec<Type>,
        pos: CodePos,
    },
    /// QUALIFIED_TYPE
    Qualified {
        /// qualified name (a.b.C)
        name: String,
        pos: CodePos,
    },
    /// OPTION_TYPE
    Option {
        /// T? inner type
        inner: Box<Type>,
        pos: CodePos,
    },
    /// CONSTANT_TYPE
    Constant {
        /// const T inner type
        inner: Box<Type>,
        pos: CodePos,
    },
    /// VARRAY_TYPE
    VArray {
        /// VArray<T> inner type
        inner: Box<Type>,
        pos: CodePos,
    },
    /// PRIMITIVE_TYPE
    Primitive {
        /// primitive kind
        kind: PrimitiveKind,
        pos: CodePos,
    },
    /// PAREN_TYPE
    Paren {
        /// parenthesized type
        inner: Box<Type>,
        pos: CodePos,
    },
    /// FUNC_TYPE
    Func {
        /// parameter types
        params: Vec<Type>,
        /// return type
        ret: Box<Type>,
        pos: CodePos,
    },
    /// TUPLE_TYPE
    Tuple {
        /// tuple element types
        elements: Vec<Type>,
        pos: CodePos,
    },
    /// THIS_TYPE
    This(CodePos),
    /// INVALID_TYPE
    Invalid(CodePos),
}

/// Pattern node.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Pattern {
    /// VAR_PATTERN
    Var {
        /// binding name
        name: String,
        /// position of the binding name token
        name_pos: CodePos,
        /// mut modifier
        is_mutable: bool,
        pos: CodePos,
    },
    /// CONST_PATTERN
    Const {
        /// literal constant (ConstPattern.literal)
        literal: Option<Box<Expr>>,
        pos: CodePos,
    },
    /// TUPLE_PATTERN
    Tuple {
        /// tuple elements
        elements: Vec<Pattern>,
        pos: CodePos,
    },
    /// ENUM_PATTERN
    Enum {
        /// constructor name
        name: String,
        /// constructor args
        args: Vec<Pattern>,
        pos: CodePos,
    },
    /// VAR_OR_ENUM_PATTERN
    VarOrEnum {
        /// name (var or enum ctor)
        name: String,
        /// args if enum ctor
        args: Vec<Pattern>,
        pos: CodePos,
    },
    /// TYPE_PATTERN
    Typed {
        /// type annotation
        ty: Type,
        pos: CodePos,
    },
    /// EXCEPT_TYPE_PATTERN
    ExceptType {
        /// excluded type
        ty: Type,
        pos: CodePos,
    },
    /// COMMAND_TYPE_PATTERN
    CommandType {
        /// effect type
        ty: Type,
        pos: CodePos,
    },
    /// WILDCARD_PATTERN
    Wildcard(CodePos),
    /// INVALID_PATTERN
    Invalid(CodePos),
}

/// Expression node.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Expr {
    /// WILDCARD_EXPR
    Wildcard(CodePos),
    /// CALL_EXPR
    Call {
        /// called expression
        callee: Box<Expr>,
        /// arguments
        args: Vec<FuncArg>,
        /// explicit type args
        type_args: Vec<Type>,
        pos: CodePos,
    },
    /// PAREN_EXPR
    Paren {
        /// parenthesized expression
        inner: Box<Expr>,
        pos: CodePos,
    },
    /// MEMBER_ACCESS
    Member {
        /// receiver
        object: Box<Expr>,
        /// member name
        name: String,
        pos: CodePos,
    },
    /// REF_EXPR
    Name {
        /// referenced name
        name: String,
        /// explicit type args
        type_args: Vec<Type>,
        pos: CodePos,
    },
    /// OPTIONAL_EXPR
    Optional {
        /// postfix ? expression
        inner: Box<Expr>,
        pos: CodePos,
    },
    /// OPTIONAL_CHAIN_EXPR
    OptionalChain {
        /// ?. chain root
        inner: Box<Expr>,
        pos: CodePos,
    },
    /// PRIMITIVE_TYPE_EXPR
    PrimitiveType {
        /// primitive type name
        kind: PrimitiveKind,
        pos: CodePos,
    },
    /// RETURN_EXPR
    Return {
        /// returned value
        value: Option<Box<Expr>>,
        pos: CodePos,
    },
    /// LIT_CONST_EXPR
    Lit {
        /// literal kind
        kind: LitKind,
        /// raw literal value
        value: String,
        pos: CodePos,
    },
    /// INTERPOLATION_EXPR
    Interpolation {
        /// interpolation parts
        parts: Vec<InterpPart>,
        pos: CodePos,
    },
    /// STR_INTERPOLATION_EXPR
    StrInterpolation {
        /// string interpolation parts
        parts: Vec<InterpPart>,
        pos: CodePos,
    },
    /// ASSIGN_EXPR
    Assign {
        /// assignment operator
        op: AssignOp,
        /// left-hand side
        lhs: Box<Expr>,
        /// right-hand side
        rhs: Box<Expr>,
        pos: CodePos,
    },
    /// UNARY_EXPR
    Unary {
        /// unary operator
        op: UnOp,
        /// operand
        inner: Box<Expr>,
        pos: CodePos,
    },
    /// BINARY_EXPR
    Binary {
        /// binary operator
        op: BinOp,
        /// left operand
        lhs: Box<Expr>,
        /// right operand
        rhs: Box<Expr>,
        pos: CodePos,
    },
    /// INC_OR_DEC_EXPR
    IncOrDec {
        /// ++ vs --
        is_inc: bool,
        /// prefix vs postfix
        is_prefix: bool,
        /// operand
        inner: Box<Expr>,
        pos: CodePos,
    },
    /// SUBSCRIPT_EXPR
    Subscript {
        /// indexed object
        object: Box<Expr>,
        /// index expression
        index: Box<Expr>,
        pos: CodePos,
    },
    /// IS_EXPR
    Is {
        /// tested expression
        inner: Box<Expr>,
        /// type
        ty: Type,
        pos: CodePos,
    },
    /// AS_EXPR
    As {
        /// casted expression
        inner: Box<Expr>,
        /// target type
        ty: Type,
        pos: CodePos,
    },
    /// RANGE_EXPR
    Range {
        /// range start
        start: Box<Expr>,
        /// range end
        end: Box<Expr>,
        /// .. vs ..=
        inclusive: bool,
        pos: CodePos,
    },
    /// ARRAY_LIT
    ArrayLit {
        /// array elements
        elements: Vec<Expr>,
        pos: CodePos,
    },
    /// ARRAY_EXPR
    Array {
        /// array expression elements
        elements: Vec<Expr>,
        pos: CodePos,
    },
    /// POINTER_EXPR
    Pointer {
        /// pointer dereference
        inner: Box<Expr>,
        pos: CodePos,
    },
    /// TUPLE_LIT
    Tuple {
        /// tuple elements
        elements: Vec<Expr>,
        pos: CodePos,
    },
    /// MATCH_EXPR
    Match {
        /// matched expression
        scrutinee: Box<Expr>,
        /// match cases
        cases: Vec<MatchCase>,
        pos: CodePos,
    },
    /// BLOCK
    Block {
        /// statements
        stmts: Vec<Expr>,
        pos: CodePos,
    },
    /// IF_EXPR
    If {
        /// condition
        cond: Box<Expr>,
        /// then branch
        then: Box<Expr>,
        /// else branch
        els: Option<Box<Expr>>,
        pos: CodePos,
    },
    /// LET_PATTERN_DESTRUCTOR
    LetPatternDestructor {
        /// patterns to be destructed
        patterns: Vec<Pattern>,
        /// initializer expression
        initializer: Box<Expr>,
        pos: CodePos,
    },
    /// TOKEN_PART
    TokenPart {
        /// token text
        text: String,
        pos: CodePos,
    },
    /// QUOTE_EXPR
    Quote {
        /// quote parts
        parts: Vec<Expr>,
        pos: CodePos,
    },
    /// TRY_EXPR
    Try {
        /// try body
        body: Box<Expr>,
        /// catch clauses
        catches: Vec<CatchClause>,
        /// finally block
        finally: Option<Box<Expr>>,
        pos: CodePos,
    },
    /// WHILE_EXPR
    While {
        /// condition
        cond: Box<Expr>,
        /// loop body
        body: Box<Expr>,
        pos: CodePos,
    },
    /// JUMP_EXPR
    Jump {
        /// break vs continue
        is_break: bool,
        pos: CodePos,
    },
    /// LAMBDA_EXPR
    Lambda {
        /// lambda parameters
        params: Vec<Param>,
        /// lambda body
        body: Box<Expr>,
        pos: CodePos,
    },
    /// TRAIL_CLOSURE_EXPR
    TrailingClosure {
        /// call receiving closure
        call: Box<Expr>,
        /// trailing closure
        closure: Box<Expr>,
        pos: CodePos,
    },
    /// FOR_IN_EXPR
    ForIn {
        /// loop pattern
        pattern: Pattern,
        /// iterated expression
        iter: Box<Expr>,
        /// loop body
        body: Box<Expr>,
        pos: CodePos,
    },
    /// DO_WHILE_EXPR
    DoWhile {
        /// condition
        cond: Box<Expr>,
        /// loop body
        body: Box<Expr>,
        pos: CodePos,
    },
    /// TYPE_CONV_EXPR
    TypeConv {
        /// target type
        ty: Type,
        /// converted expression
        inner: Box<Expr>,
        pos: CodePos,
    },
    /// THROW_EXPR
    Throw {
        /// thrown expression
        inner: Box<Expr>,
        pos: CodePos,
    },
    /// PERFORM_EXPR
    Perform {
        /// performed expression
        inner: Box<Expr>,
        pos: CodePos,
    },
    /// RESUME_EXPR
    Resume {
        /// resumed expression
        inner: Box<Expr>,
        pos: CodePos,
    },
    /// SPAWN_EXPR
    Spawn {
        /// spawned block
        inner: Box<Expr>,
        pos: CodePos,
    },
    /// SYNCHRONIZED_EXPR
    Synchronized {
        /// synchronized block
        inner: Box<Expr>,
        pos: CodePos,
    },
    /// MACRO_EXPAND_EXPR
    MacroExpand {
        /// macro name
        name: String,
        /// macro args
        args: Vec<Tokenish>,
        pos: CodePos,
    },
    /// IF_AVAILABLE_EXPR
    IfAvailable {
        /// feature list
        features: Vec<String>,
        /// then branch
        then: Box<Expr>,
        /// else branch
        els: Option<Box<Expr>>,
        pos: CodePos,
    },
    /// INVALID_EXPR
    Invalid(CodePos),
}

/// Declaration node.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Decl {
    /// MAIN_DECL
    Main {
        /// function body
        body: Body,
        pos: CodePos,
    },
    /// FUNC_DECL
    Func {
        /// function name
        name: String,
        /// position of the function name token (start of the identifier)
        name_pos: CodePos,
        /// public modifier
        is_public: bool,
        /// abstract modifier
        is_abstract: bool,
        /// generic parameters
        type_params: Vec<TypeParam>,
        /// parameters
        params: Vec<Param>,
        /// return type
        ret: Option<Type>,
        /// function body
        body: Body,
        pos: CodePos,
    },
    /// MACRO_DECL
    Macro {
        /// macro name
        name: String,
        /// public modifier
        is_public: bool,
        /// parameters
        params: Vec<Param>,
        /// macro body
        body: Body,
        pos: CodePos,
    },
    /// CLASS_DECL
    Class {
        /// class name
        name: String,
        /// position of the class name token
        name_pos: CodePos,
        /// public modifier
        is_public: bool,
        /// abstract modifier
        is_abstract: bool,
        /// open modifier
        is_open: bool,
        /// sealed modifier
        is_sealed: bool,
        /// generic parameters
        type_params: Vec<TypeParam>,
        /// parent types (<: A, B)
        parents: Vec<Type>,
        /// class members
        members: Vec<Decl>,
        pos: CodePos,
    },
    /// INTERFACE_DECL
    Interface {
        /// interface name
        name: String,
        /// position of the interface name token
        name_pos: CodePos,
        /// public modifier
        is_public: bool,
        /// generic parameters
        type_params: Vec<TypeParam>,
        /// parent interfaces
        parents: Vec<Type>,
        /// interface members
        members: Vec<Decl>,
        pos: CodePos,
    },
    /// EXTEND_DECL
    Extend {
        /// public modifier
        is_public: bool,
        /// extended type
        target: Type,
        /// extension members
        members: Vec<Decl>,
        pos: CodePos,
    },
    /// ENUM_DECL
    Enum {
        /// enum name
        name: String,
        /// position of the enum name token
        name_pos: CodePos,
        /// public modifier
        is_public: bool,
        /// generic parameters
        type_params: Vec<TypeParam>,
        /// enum cases
        cases: Vec<EnumCase>,
        pos: CodePos,
    },
    /// STRUCT_DECL
    Struct {
        /// struct name
        name: String,
        /// position of the struct name token
        name_pos: CodePos,
        /// public modifier
        is_public: bool,
        /// open modifier
        is_open: bool,
        /// generic parameters
        type_params: Vec<TypeParam>,
        /// struct members
        members: Vec<Decl>,
        pos: CodePos,
    },
    /// TYPE_ALIAS_DECL
    TypeAlias {
        /// alias name
        name: String,
        /// public modifier
        is_public: bool,
        /// aliased type
        target: Type,
        pos: CodePos,
    },
    /// PRIMARY_CTOR_DECL
    PrimaryCtor {
        /// public modifier
        is_public: bool,
        /// constructor parameters
        params: Vec<Param>,
        /// constructor body
        body: Body,
        pos: CodePos,
    },
    /// BUILTIN_DECL
    Builtin {
        /// builtin decl name
        name: String,
        pos: CodePos,
    },
    /// VAR_DECL
    Var {
        /// variable name
        name: String,
<<<<<<< HEAD
        /// position of the binding name token
=======
        /// position of the variable name token
>>>>>>> wt/t3-unused-members
        name_pos: CodePos,
        /// var vs let
        is_mutable: bool,
        /// public modifier
        is_public: bool,
        /// declared type
        ty: Option<Type>,
        /// initializer
        init: Option<Expr>,
        pos: CodePos,
    },
    /// PROP_DECL
    Prop {
        /// property name
        name: String,
        /// public modifier
        is_public: bool,
        /// static modifier
        is_static: bool,
        /// property type
        ty: Type,
        pos: CodePos,
    },
    /// FUNC_PARAM
    FuncParam {
        /// parameter name
        name: String,
        /// named-call parameter (a!:)
        is_named: bool,
        /// parameter type
        ty: Type,
        /// default value
        default: Option<Expr>,
        pos: CodePos,
    },
    /// VAR_WITH_PATTERN_DECL
    VarWithPattern {
        /// destructuring pattern
        pattern: Pattern,
        /// declared type
        ty: Option<Type>,
        /// initializer
        init: Option<Expr>,
        pos: CodePos,
    },
    /// GENERIC_PARAM_DECL
    GenericParam {
        /// type parameter name
        name: String,
        /// constraints (where T <: X)
        bounds: Vec<Type>,
        pos: CodePos,
    },
    /// PACKAGE_DECL
    Package {
        /// package name
        name: String,
        pos: CodePos,
    },
    /// MACRO_EXPAND_DECL
    MacroExpand {
        /// macro name
        name: String,
        /// macro arguments
        args: Vec<Tokenish>,
        pos: CodePos,
    },
    /// INVALID_DECL
    Invalid(CodePos),
}

/// Placeholder for macro arguments (token-level; refined with macro support).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Tokenish {
    pub text: String,
    pub pos: CodePos,
}
